server:
  port: 8010
spring:
  application:
    name: comment-service
  datasource:
    url: jdbc:mysql://localhost:3306/commentdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"